package io.skein.classify.application

import io.skein.classify.domain.MultiLabelDatasetSplit
import io.skein.classify.domain.MultiLabeledFeatures

/** Cross-validation needs at least a train and a test fold. */
private const val MIN_FOLDS = 2

/** Seed used when the caller does not supply one, so a split is reproducible by default. */
private const val DEFAULT_SEED = 42L

// SplitMix64, used only to spread group names that share a prefix. The shift distances are part of
// the published algorithm, not tuning.
private const val GOLDEN_GAMMA = -0x61c8864680b583ebL
private const val MIX_A = -0x40a7b892e31b1a47L
private const val MIX_B = -0x6b2fb644ecceee15L
private const val MIX_SHIFT_A = 30
private const val MIX_SHIFT_B = 27
private const val MIX_SHIFT_C = 31

/**
 * Partitions a corpus so that every row sharing an origin lands in the same fold.
 *
 * **Why this exists, in one measurement.** When training data is generated by a rule engine — the
 * whole rule-distillation workflow — every example of one rule contains that rule's keyword.
 * [StratifiedSplitter], or any random split, puts siblings on both sides, so the model reads the
 * answer off the training set and the score measures memorisation. On the reference corpus that is
 * micro-F1 **0.79 random against 0.75 grouped**, and macro-F1 **0.634 against 0.534**. The grouped
 * number is the honest one, and the gap is the size of the lie.
 *
 * The assignment mirrors scikit-learn's `GroupKFold`: largest groups first, each into whichever
 * fold currently holds the fewest rows. That is greedy rather than optimal, and it balances well
 * when group sizes are uneven, which is exactly when balance is hard.
 *
 * Deterministic, but **not** by group name. Groups are visited by descending size and then in an
 * order derived from a fixed [seed], so the same corpus splits identically however its rows happen
 * to be ordered — which matters, because row order in a `.skein` file follows ingestion.
 *
 * Visiting equal-sized groups in plain alphabetical order would be simpler and is what a naive
 * implementation does, including scikit-learn's. It has a trap: group names usually encode
 * structure, so alphabetical order correlates with that structure, and round-robin over it can line
 * a fold up with a whole category. Groups named `<cuisine>/<protein>/<method>` over five methods,
 * split into five folds, put **every** `one pot` group in one fold — so the label that depends on
 * that method was absent from four folds' training data and scored zero recall, for reasons that
 * had nothing to do with the model. Ordering by a seeded mix of the name instead decorrelates the
 * assignment from whatever the names happen to encode, while staying reproducible.
 *
 * Rows with no group are singletons, and those *are* order-dependent, since nothing else
 * distinguishes them.
 */
class GroupedSplitter(private val seed: Long = DEFAULT_SEED) {

    /**
     * Assigns each entry of [groups] to one of [folds], returning the fold index per position.
     *
     * The primitive both the feature-level and the text-level splits are built from, so a caller
     * that needs to split something else — raw records, or rows plus a parallel array — can use the
     * same balancing without this class knowing about its type.
     *
     * A `null` group is a group of one.
     */
    fun assign(groups: List<String?>, folds: Int): IntArray {
        require(value = groups.isNotEmpty()) { "cannot split an empty corpus" }
        require(value = folds >= MIN_FOLDS) { "folds must be at least $MIN_FOLDS, got $folds" }
        require(value = folds <= groups.size) {
            "cannot build $folds folds from ${groups.size} rows"
        }
        val members = membersByGroup(groups = groups)
        val ordered = members.entries.sortedWith(
            comparator = compareByDescending<Map.Entry<String, List<Int>>> { entry -> entry.value.size }
                .thenBy { entry -> scramble(key = entry.key) }
                .thenBy { entry -> entry.key },
        )
        val assignment = IntArray(size = groups.size)
        val load = IntArray(size = folds)
        ordered.forEach { entry ->
            val lightest = lightestFold(load = load)
            entry.value.forEach { position -> assignment[position] = lightest }
            load[lightest] += entry.value.size
        }
        return assignment
    }

    /**
     * Builds [folds] train/holdout splits of [observations], each holding out one fold.
     *
     * Every observation is held out exactly once across the returned splits, so pooling their
     * outcomes gives an honest reading over the whole corpus.
     */
    fun folds(observations: List<MultiLabeledFeatures>, folds: Int): List<MultiLabelDatasetSplit> {
        val assignment = assign(groups = observations.map { observation -> observation.group }, folds = folds)
        return (0 until folds).map { fold ->
            val training = ArrayList<MultiLabeledFeatures>(observations.size)
            val holdout = ArrayList<MultiLabeledFeatures>()
            observations.indices.forEach { position ->
                if (assignment[position] == fold) {
                    holdout.add(element = observations[position])
                } else {
                    training.add(element = observations[position])
                }
            }
            MultiLabelDatasetSplit(training = training, holdout = holdout)
        }
    }

    /**
     * Groups as position lists. Ungrouped rows become singletons under a key that cannot collide
     * with a caller's group name, so a corpus mixing grouped and ungrouped rows behaves sensibly.
     */
    private fun membersByGroup(groups: List<String?>): Map<String, List<Int>> {
        val members = LinkedHashMap<String, MutableList<Int>>()
        groups.forEachIndexed { position, group ->
            val key = group ?: "\u0000ungrouped-$position"
            members.getOrPut(key = key) { ArrayList() }.add(element = position)
        }
        return members
    }

    /**
     * A stable, seed-dependent ordering key for a group name.
     *
     * `String.hashCode` is specified by the language, so this is reproducible across machines and
     * JVM versions; the SplitMix64 finalizer then spreads names that share a prefix, which plain
     * hash codes do not. The group name itself remains the final tie-break, so two names that
     * collide here still order deterministically.
     */
    private fun scramble(key: String): Long {
        var mixed = key.hashCode().toLong() * GOLDEN_GAMMA + seed
        mixed = (mixed xor (mixed ushr MIX_SHIFT_A)) * MIX_A
        mixed = (mixed xor (mixed ushr MIX_SHIFT_B)) * MIX_B
        return mixed xor (mixed ushr MIX_SHIFT_C)
    }

    private fun lightestFold(load: IntArray): Int {
        var lightest = 0
        load.indices.forEach { fold ->
            if (load[fold] < load[lightest]) {
                lightest = fold
            }
        }
        return lightest
    }
}
