package io.skein.classify.infrastructure

import io.skein.classify.domain.SparseMatrix
import io.skein.classify.domain.SparseMatrixBuilder
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json

/**
 * The logistic problem in `src/test/resources/reference/logistic-reference.json`, together with the
 * optimum an independent Newton solver reached on it.
 *
 * The fixture is generated by `logistic_reference.py` beside it, which documents why the reference
 * is a Newton solve rather than scikit-learn's returned coefficients. Its feature values are
 * multiples of 2^-10, so they survive the `float` storage in [SparseMatrix] exactly and the two
 * solvers are answering the same question rather than two roundings of it.
 */
@Serializable
internal data class LogisticReferenceProblem(
    val inverseRegularization: Double,
    val featureCount: Int,
    val rows: List<List<Double>>,
    val labels: List<Int>,
    val optimum: List<Double>,
    val optimalValue: Double,
    val gradientNormAtOptimum: Double,
) {

    /** The design matrix, dense rows stored sparsely — every feature of every row is non-zero. */
    fun matrix(): SparseMatrix {
        val builder = SparseMatrixBuilder(columnCount = featureCount)
        rows.forEach { row ->
            builder.addRow(
                columnIndices = IntArray(size = featureCount) { index -> index },
                values = FloatArray(size = featureCount) { index -> row[index].toFloat() },
                from = 0,
                to = featureCount,
            )
        }
        return builder.build()
    }

    /** Row indices carrying the positive class, ascending, as [LogisticObjective] expects. */
    fun positiveRows(): IntArray {
        return labels.indices.filter { index -> labels[index] == 1 }.toIntArray()
    }

    fun objective(): LogisticObjective {
        return LogisticObjective(
            matrix = matrix(),
            positiveRows = positiveRows(),
            inverseRegularization = inverseRegularization,
        )
    }

    internal companion object {

        fun load(): LogisticReferenceProblem {
            val stream = LogisticReferenceProblem::class.java
                .getResourceAsStream("/reference/logistic-reference.json")
            checkNotNull(value = stream) { "reference/logistic-reference.json is missing from the test resources" }
            return stream.use { input ->
                Json.decodeFromString(
                    deserializer = serializer(),
                    string = input.readBytes().decodeToString(),
                )
            }
        }
    }
}
